import './Home.css';

const Home = () => {
    return (
        <div>
            <h1>Home</h1>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Veritatis assumenda iure quo, perspiciatis odit vitae officia distinctio neque quam esse id accusantium deleniti repellat quod voluptas illo repellendus quas quaerat natus nihil placeat dolore? Reiciendis laborum iusto, consectetur incidunt aspernatur labore tempore voluptatum velit enim accusamus voluptas recusandae nesciunt molestias quia eligendi id saepe iste ipsam quidem culpa? Inventore molestias beatae a odit natus sed repellendus odio voluptates similique. Fugiat aliquid architecto, vero recusandae dolore deserunt doloribus temporibus eum delectus voluptatibus ad id saepe, molestiae ut accusamus, quasi mollitia officia debitis eius amet velit iure alias! Error tenetur sit aperiam! Pariatur, necessitatibus! Voluptas molestias impedit quisquam vel ab ducimus animi exercitationem dolore! Esse iure numquam harum, reprehenderit deserunt dicta odio in quibusdam dolore optio, minima qui nesciunt. Enim veritatis autem corrupti consectetur voluptate, corporis velit id asperiores vero, cupiditate, ducimus eaque amet atque? Amet natus dolore nulla, sit asperiores quod facere labore ex, quia repellat vero illum fugiat ut accusamus. Natus dignissimos quisquam quos fuga aliquam magnam. Ullam repudiandae vero odio repellat voluptatem eum veniam. Cumque ea maiores, obcaecati, doloremque voluptatem voluptates hic labore recusandae necessitatibus vel eum quasi consequuntur molestiae inventore provident blanditiis officia libero pariatur praesentium dolor quae?</p>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Veritatis assumenda iure quo, perspiciatis odit vitae officia distinctio neque quam esse id accusantium deleniti repellat quod voluptas illo repellendus quas quaerat natus nihil placeat dolore? Reiciendis laborum iusto, consectetur incidunt aspernatur labore tempore voluptatum velit enim accusamus voluptas recusandae nesciunt molestias quia eligendi id saepe iste ipsam quidem culpa? Inventore molestias beatae a odit natus sed repellendus odio voluptates similique. Fugiat aliquid architecto, vero recusandae dolore deserunt doloribus temporibus eum delectus voluptatibus ad id saepe, molestiae ut accusamus, quasi mollitia officia debitis eius amet velit iure alias! Error tenetur sit aperiam! Pariatur, necessitatibus! Voluptas molestias impedit quisquam vel ab ducimus animi exercitationem dolore! Esse iure numquam harum, reprehenderit deserunt dicta odio in quibusdam dolore optio, minima qui nesciunt. Enim veritatis autem corrupti consectetur voluptate, corporis velit id asperiores vero, cupiditate, ducimus eaque amet atque? Amet natus dolore nulla, sit asperiores quod facere labore ex, quia repellat vero illum fugiat ut accusamus. Natus dignissimos quisquam quos fuga aliquam magnam. Ullam repudiandae vero odio repellat voluptatem eum veniam. Cumque ea maiores, obcaecati, doloremque voluptatem voluptates hic labore recusandae necessitatibus vel eum quasi consequuntur molestiae inventore provident blanditiis officia libero pariatur praesentium dolor quae?</p>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Veritatis assumenda iure quo, perspiciatis odit vitae officia distinctio neque quam esse id accusantium deleniti repellat quod voluptas illo repellendus quas quaerat natus nihil placeat dolore? Reiciendis laborum iusto, consectetur incidunt aspernatur labore tempore voluptatum velit enim accusamus voluptas recusandae nesciunt molestias quia eligendi id saepe iste ipsam quidem culpa? Inventore molestias beatae a odit natus sed repellendus odio voluptates similique. Fugiat aliquid architecto, vero recusandae dolore deserunt doloribus temporibus eum delectus voluptatibus ad id saepe, molestiae ut accusamus, quasi mollitia officia debitis eius amet velit iure alias! Error tenetur sit aperiam! Pariatur, necessitatibus! Voluptas molestias impedit quisquam vel ab ducimus animi exercitationem dolore! Esse iure numquam harum, reprehenderit deserunt dicta odio in quibusdam dolore optio, minima qui nesciunt. Enim veritatis autem corrupti consectetur voluptate, corporis velit id asperiores vero, cupiditate, ducimus eaque amet atque? Amet natus dolore nulla, sit asperiores quod facere labore ex, quia repellat vero illum fugiat ut accusamus. Natus dignissimos quisquam quos fuga aliquam magnam. Ullam repudiandae vero odio repellat voluptatem eum veniam. Cumque ea maiores, obcaecati, doloremque voluptatem voluptates hic labore recusandae necessitatibus vel eum quasi consequuntur molestiae inventore provident blanditiis officia libero pariatur praesentium dolor quae?</p>
        </div>
    );
};

export default Home;